### PR TITLE
Pushing different markers

### PR DESCRIPTION
**Pull request by JaneJiangHH**
#72 each player has a different marker for each round;
and after each round, wait for other players' markers to  be pushed;
But have problems with pushing other players' markers(only works for one player and timer doesn't works fine)

### CODE REVIEW

**Comment by blanche** [comment]
this should be squash committed because of the webapp folder in 47d36c4

**Comment by JaneJiangHH** [comment]
squash committed? means I should squash and merge after approved?

**Comment by blanche** [comment]
yep :)

its just so we don't have the compiled binaries in the repo history

**Comment by JaneJiangHH** [comment]
sure i will do that, but need someone to approve my pull request first

**Comment by blanche** [comment]
i am just looking at it, but the removal of creating a player will break the join-component by @andreaseliasson :/

**Comment by JaneJiangHH** [comment]
ah yes, but there is a problem with player component, it will not show player's created name on the first try

**Comment by blanche** [comment]
i checked in a temporary fix on this branch to make it work, because i need it to work for syncing up the games but can either of you @JaneJiangHH or @andreaseliasson look at how to this properly? 

problem is at JoinComponent.join we dont have the player_id in the route anymore, because the player is created when creating a game, but not when joining one
so we (1) have an extra step to create the player everytime or (2) create the player when joining the game

**Comment by JaneJiangHH** [comment]
use (2) so join component and player component are not used. Please check

**Comment by andreaseliasson** [comment]
What should we do here? Should we be pragmatic and turn off the player and join component as with the latest commit in this branch?

We are short on time, so it's ok for me.

**Comment by JaneJiangHH** [comment]
Xin said she would like method (1), if she did that, we could change it later or we can discuss in tomorrow's meeting.

**Review by stellaxxiang — APPROVED** [review]
approve

**Pull request merged**
