### PR TITLE
Core/angular typescript skeleton

### PR DESCRIPTION
**Pull request by andreaseliasson**
Basic angular skeleton in typescript, using webpack as the module bundler, and karma for running unit tests.

This skeleton is based on the official angular documentation for using webpack --> https://angular.io/docs/ts/latest/guide/webpack.html

When checking out this branch, you should be able to get the app up and running by:
1. `npm install`
2. `npm start`
3. Go to localhost:8080

### CODE REVIEW

**Comment by blanche** [comment]
webpack sounds interesting! Is it used instead-of or in-addition-to other build tools like gulp?

**Comment by andreaseliasson** [comment]
Webpack can be used both as a module bundler and build tool. This way we can configure just about anything using webpack so we won't need any extra build tool, e.g. grunt or gulp.

**Comment by andreaseliasson** [comment]
Add a root directory for the frontend code.

**Comment by blanche** [comment]
Can't see the new root dir :?

**Comment by andreaseliasson** [comment]
It's a task so it hasn't been implemented yet. I guess we should have two directories within the root directory, one for all the frontend code and one for all the backend code?

**Review by blanche — APPROVED** [review]
lgtm

**Pull request merged**
