### PR TITLE
Map style

### PR DESCRIPTION
**Pull request by stellaxxiang**
Added basic map styling method and makes marker changing color

### CODE REVIEW

**Comment by andreaseliasson** [comment]
For some reason I can only see a part of the map when playing the game. Like so: 
screen shot 2016-12-22 at 08 22 52

**Comment by JaneJiangHH** [comment]
This works fine on my computer, only with the problem that the map is a little smaller than origin.

**Comment by utkuozbulak** [comment]
@andreaseliasson  Works fine for me ?

image

**Comment by stellaxxiang** [comment]
@andreaseliasson it works fine for me as well.... 
image
Cause I changed the class of city name to col-md-3 as Hong-Kong couldn't show on one line before.

**Review by utkuozbulak — APPROVED** [review]
Looks good, not sure why Andreas is having issues.

**Comment by blanche** [comment]
there is an issue with different window sizes, it only works for some resoltions

**Comment by blanche** [comment]
also zooming was disabled? why?

**Pull request merged**
