### PR TITLE
Core/angular skeleton extended

### PR DESCRIPTION
**Pull request by andreaseliasson**
This is an extended version of the already implemented skeleton. This branch include modules (es6) and the webpack tool for bundling all files into one big static file.
#20 #21

### CODE REVIEW

**Comment by stellaxxiang** [comment]
Are these all the files that are able to open a basic web page? I can only get 'Loading...' from localhost:8080....

**Comment by andreaseliasson** [comment]
Should be.. Do you have any error messages in the console?

**Comment by stellaxxiang** [comment]
No. The problem was that I combined the js-src/ files and the original angular skeleton together...

**Comment by blanche** [comment]
which of the two main.js files are we going to use? Can we get rid of one of them?

**Comment by andreaseliasson** [comment]
Redundant main.js file has been removed. We should try and merge this branch asap.

**Review by blanche — APPROVED** [review]
lgtm

**Pull request merged**
